### ISSUE TITLE
Installation Windows7

### ISSUE THREAD

**Issue by paolosaudin** [commandprompt/pgmanage#176]
I Installed 1.0b2 version on Windows7, all went fine. When I run the app an error message pops up saying "python39.dll not found" when actually exists.

Thank,
![pgmanage](https://github.com/commandprompt/pgmanage/assets/122820091/9166003f-0e4e-477c-9b6c-b8bd5596fcaf)

paolo

**Comment by eug3nix** [comment]
Hi @paolosaudin 
While Windows 7 is and end of life OS since 2020 and it is not supported by Pgamange, I think that the mentioned issue may be related to your CPU architecture. Pgmanage Windows build only supports x86_64 CPU/OS combo.

Thank you for your feedback, we will consider adding extra checks to the Windows installer so it would not proceed on older/unsupported systems. The official documentation also should be updated to clearly state which OS versions are supported.

**Comment by paolosaudin** [comment]
Thank you very much Eugene!
I'll try on another platform

Regards,
Paolo

Il giorno mar 25 lug 2023 alle ore 09:45 Eugene ***@***.***>
ha scritto:

**Comment by eug3nix** [comment]
OS version check added to the windows installer, closing the ticket.
