### ISSUE TITLE
Nginx PG_MANAGE -- Help

### ISSUE THREAD

**Issue by jdelramirez** [commandprompt/pgmanage#400]
Good morning,

I'm running the development environment but I can't get it to work correctly, I'm using nginx to redirect ports 8000 and 3000, but it still gives a conflict and the tool doesn't load properly.

![image](https://github.com/commandprompt/pgmanage/assets/63667271/b6d343fc-7333-4b36-a715-e014210ad6f0)

server {
    
     
    location / {
      proxy_pass http://127.0.0.1:8000;
      proxy_redirect off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
   }

    location /static {
      proxy_pass http://127.0.0.1:3000;
      proxy_redirect off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
   }
}

how can i do it ? i see in port 8000 load someconfigs in /static and nodejs server have /static resources too, any helps ?

Thanks for all

**Comment by eug3nix** [comment]
Hi. I have not tested similar setups myself (and unfortunately I don't have time to test such unsupported configurations).
The possible cause of your issue is that static file URLs in the generated web page are still pointing to localhost:3000 (as defined in vite.config.js). You can take a look at page sources to figure this out. Potentially you can do some postprocessing in nginx to rewrite static resource urls with your webserver address. This approach is very hacky though.
Please note that you're basically trying to use development environment as a prod-like web service, which I do not recomment due to many limitations and potential issues.
