### ISSUE TITLE
Connection String Oracle - Pgmanage 1.1

### ISSUE THREAD

**Issue by jdelramirez** [commandprompt/pgmanage#460]
Good morning, I am still encountering the same error. 

![image](https://github.com/user-attachments/assets/bc35fc84-b02d-46b4-b585-8c227b89b6db)

I have downloaded the version you indicated, 1.1 for Unix, followed all the same steps, and installed the requirements, but I cannot get the connection string to work correctly. 

is a change of this file ? ./app/include/OmniDatabase/Oracle.py ?

/python3.9/site-packages/oracledb-1.3.1.dist-info

Could you please assist me? Thank you

_Originally posted by @jdelramirez in https://github.com/commandprompt/pgmanage/issues/431#issuecomment-2301358334_

**Comment by eug3nix** [comment]
Hello
I've tried to reproduce this issue using 1.1 release in .appimage format and it does not produce such error.
Can you check if .AppImage distribution works in your environment?

**Comment by jdelramirez** [comment]
Good afternoon, first of all, thank you for your response eug3nix. On the other hand, I want to let you know that I don't use the AppImage since I use a server without a graphical interface. Therefore, what I do is download the source code and run it as indicated, with npm and Python :(

**Comment by eug3nix** [comment]
Hi.
The fix for the mentioned issue was introduced in this commit: https://github.com/commandprompt/pgmanage/commit/be32e0c4d363ae60698c4d1ca43b29138562a3c8
So please make sure that your local working copy of the code is actually at the correct revision.
Alternatively you can extract pgmanage-server from .appimage distribution and run in in a web-server configuration.
Please note that all such configurations are not supported and we can not spend much time troubleshooting the issues with such unconventional pgmanage set-ups.

**Comment by jdelramirez** [comment]
Thanks! The connection is established, but it's behaving unexpectedly. The password is included in the connection string, yet the system still prompts for it two times and doesn't list database objects properly. I've tried the same connection string in MySQL and encountered the same issue: a password prompt for the schema. Thanks for your help!


![image](https://github.com/user-attachments/assets/1d46f8e3-0c2b-4490-acb1-42f2e5e7586b)

![image](https://github.com/user-attachments/assets/a66e4587-8305-4367-891a-5c2e2ffc0953)
